"""Configuration file.

This file is execfile()d with the current directory set to its containing dir.

Note that not all possible configuration values are present in this
autogenerated file.

All configuration values have a default; values that are commented out
serve to show the default.
"""

import os
import sys

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "eor-limits"  # The name of the project.
master_doc = "index"  # The master toctree document.
copyright = "2025, Nichole Barry & Bryna Hazelton"  # noqa: A001
author = "Nichole Barry & Bryna Hazelton"
try:
    from eor_limits import __version__ as version
except ImportError:
    pass
else:
    release = version  # The short X.Y version.

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.ifconfig",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "numpydoc",
    "nbsphinx",
    "IPython.sphinxext.ipython_console_highlighting",
    # "sphinx_click",
    "myst_parser",
]

# Autosummary
autosummary_generate = True  # Automatically generate summary files for documented items
# Autodoc
autodoc_typehints = "none"  # No type hints, let numpydoc handle them in the docstrings
# Numpydoc
numpydoc_show_class_members = False  # Don't show class members by default
numpydoc_class_members_toctree = False  # Don't create toctree for class members
numpydoc_xref_param_type = True  # Enable cross-referencing for parameter types
# Napoleon
napoleon_use_ivar = True  # Use instance variables for attributes
napoleon_use_rtype = False  # Don't use rtype for return types (use :returns:)
napoleon_use_param = False  # Don't use :param: for parameters (use :Parameters:)
# MathJax
mathjax_path = (
    "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
)
# Intersphinx
python_version = ".".join(map(str, sys.version_info[:2]))
intersphinx_mapping = {
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "python": (f"https://docs.python.org/{python_version}", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}
# Templates path.
templates_path = ["_templates"]
# The suffix of source filenames.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"
pygments_dark_style = "monokai"
# Exclude patterns.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "_templates",
    "**.ipynb_checkpoints",
]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

on_rtd = os.environ.get("READTHEDOCS", None) == "True"  # whether on readthedocs.org
html_theme = "sphinx_book_theme"
html_theme_options = {
    "show_navbar_depth": 2,
    "show_prev_next": False,
    "repository_url": "https://github.com/steven-murray/eor_limits",
    "repository_branch": "main",
    "path_to_docs": "docs",
    "use_repository_button": True,
    "use_issues_button": True,
    "secondary_sidebar_items": [],
}
html_static_path = ["_static"]
html_css_files = ["custom.css"]


# -- Options for LaTeX output --------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-latex-output

latex_elements = {}
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    (
        "index",
        "user_guide.tex",
        "eor-limits Documentation",
        "Nichole Barry & Bryna Hazelton",
        "manual",
    ),
]
