"""Configuration file.

This file is execfile()d with the current directory set to its containing dir.

Note that not all possible configuration values are present in this
autogenerated file.

All configuration values have a default; values that are commented out
serve to show the default.
"""

import os
import sys

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "eor-limits"  # The name of the project.
master_doc = "index"  # The master toctree document.
copyright = (  # noqa: A001
    "2019 (Nichole Barry & Bryna Hazelton), "
    "2026 (Jiten Dhandha, Steven Murray & all contributors)"
)

author = "Jiten Dhandha, Steven Murray, Nichole Barry, Bryna Hazelton"
try:
    from eor_limits import __version__ as version
except ImportError:
    pass
else:
    release = version  # The short X.Y version.

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.coverage",
    "sphinx.ext.doctest",
    "sphinx.ext.ifconfig",
    "sphinx.ext.mathjax",
    "numpydoc",
    "nbsphinx",
    "IPython.sphinxext.ipython_console_highlighting",
    # "sphinx_click",
    "myst_parser",
]

# Autosummary
autosummary_generate = True  # Automatically generate summary files for documented items
# nbsphinx
nbsphinx_kernel_name = "python3"  # Use the standard Python kernel for notebook builds
# Autodoc
autodoc_typehints = "none"  # No type hints, let numpydoc handle them in the docstrings
# Numpydoc
numpydoc_show_class_members = False  # Don't show class members by default
numpydoc_class_members_toctree = False  # Don't create toctree for class members
numpydoc_xref_param_type = True  # Enable cross-referencing for parameter types
numpydoc_xref_aliases = {
    "np.ndarray": "numpy.ndarray",
    "Path": "pathlib.Path",
    "Any": "typing.Any",
}  # Map common aliases to full module paths for linking
# MathJax v3
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
# Global substitutions available in rst/docstrings.
rst_prolog = """
.. |z| replace:: :math:`z`
.. |k| replace:: :math:`k`
.. |delta| replace:: :math:`\\Delta_{21}`
.. |dsq| replace:: :math:`\\Delta_{21}^2`
.. |mK^2| replace:: :math:`\\mathrm{mK}^2`
.. |h/Mpc| replace:: :math:`h\\,\\mathrm{Mpc}^{-1}`
"""
# Intersphinx
python_version = ".".join(map(str, sys.version_info[:2]))
intersphinx_mapping = {
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "python": (f"https://docs.python.org/{python_version}", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}
# MyST-parser
myst_enable_extensions = ["dollarmath"]
# Templates path.
templates_path = ["_templates"]
# The suffix of source filenames.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"
pygments_dark_style = "monokai"
# Exclude patterns.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "_templates",
    "**.ipynb_checkpoints",
]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

on_rtd = os.environ.get("READTHEDOCS", None) == "True"  # whether on readthedocs.org
html_theme = "sphinx_book_theme"
html_theme_options = {
    "show_navbar_depth": 2,
    "show_prev_next": False,
    "repository_url": "https://github.com/steven-murray/eor_limits",
    "repository_branch": "main",
    "path_to_docs": "docs",
    "use_repository_button": True,
    "use_issues_button": True,
    "secondary_sidebar_items": [],
}
html_static_path = ["_static"]
html_css_files = ["custom.css"]
