name: Tests

on:
  pull_request:


jobs:
  tests:
    env:
      ENV_NAME: tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13", "3.14"]
        uv-options: ["--frozen"]
        include:
          - uv-options: "--upgrade"
            python-version: "3.14"
            os: "ubuntu-latest"
          - uv-options: "--resolution lowest-direct"
            python-version: "3.12"
            os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.26"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync ${{ matrix.uv-options }} --all-extras --dev

      - name: Run Tests
        run: |
          uv run --no-sync pytest --cov eor_limits --cov-report xml:coverage.xml

      - uses: codecov/codecov-action@v7
        if: success()
        with:
          files: ./coverage.xml #optional
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
